deploy:
  provider: heroku
  api_key:
    secure: MrD3zpOIpC1eUkDGYDsMyUWzBvKVmf/q3gf+TWytTpBKUNU+YULsYS8hPfyedgDemsTD0s9OQHv5WHbdH62cmo5LDRn5003+2OTJ/+GdZAcZb6LD/i1jpzPqPtZYMjgm/S2Osa7ao4PwbmXdnQbkpl1b7udeueTANf7JN8zvRIn3IGJVKm6pn+QIFXqGTvH4c7VLJhZ4t/6BlEYL4e8hUO7U7i/t+e8P5S9dykFfdex5bOa26msc+TQM/l+SULHjd9e6M1ueXtbAthRqX7pMRqHC/Iepu7onuc404D1HEOu+JbYWkLd+VDKTDr2sExuckY10VVbxUdS81368Q192e4ZRvqXAFJPcHh4hYLb9JdrOQcIAX+WGTxC6EZS8iWjnT4ZLK3++EDXfF0NuAdwYwilM/v6FwAdAczbTMsawPDGZOJuJgjodjxBlzunuVAAweyI02cRsE2mEc7TuVmEmhZUMEY4taprv5co9mN6jX3DMwAnmddCqparLnMhm5iKsg12BCxG5CAn6sN2AqQ1XEc3QhNd5smN7JxGOS5QN7mtrycSn3bzuxFKLoKNCyBIq9eLQ7JDBCxIyZ+vKBkLCJBW1eK0QQizYQs5QVduRjZ+Xfo+Q/igvicFb1MXHsCXMI6HmNW9a6oRXIf3JzIapc8jjjYhwqZZnoE6jrGA8huk=
  app: whispering-garden-8175
  on:
    repo: gef756/heroku-scala-getting-started
